# Example of INL calculation

In [1]:
%matplotlib widget
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
from scipy import stats

create variable to select the reference source

In [2]:
# source = Fluke 5720A
# dutb = HP3458A
ref = "source"

load Transmille measurement from xdevs server

it doesn't matter if the source is your local file system or a web address

In [3]:
data = pd.read_csv("https://xdevs.com/doc/Transmille/8104/3458_vs_8104/dcl_10vdc_5720_8104r_3458a_nlpc100_raw_jul2021.csv", sep=";")
data

,date,source,duta,dutb,dutc,dutd,sdev,sdev2,sdev3,sdev4,temp,temp2,ambt,rh,pressure,Unnamed: 15
0,08042021-00:54:11,-10.9,-10.899970,-10.900027,-10.9,0.0,0.000000e+00,6.500000e-08,0.000000e+00,0,35.0,23.0,23.017,"59.64,992.47",NaN,NaN
1,08042021-00:54:18,-10.9,-10.899968,-10.900027,-10.9,0.0,8.956690e-07,1.710750e-07,0.000000e+00,0,35.0,23.0,23.011,"59.66,992.46",NaN,NaN
2,08042021-00:54:25,-10.9,-10.899968,-10.900027,-10.9,0.0,9.500000e-07,1.491640e-07,0.000000e+00,0,35.0,23.0,23.001,"59.70,992.45",NaN,NaN
3,08042021-00:54:32,-10.9,-10.899970,-10.900027,-10.9,0.0,9.308060e-07,1.905150e-07,0.000000e+00,0,35.0,23.0,22.992,"59.70,992.49",NaN,NaN
4,08042021-00:54:39,-10.9,-10.899970,-10.900027,-10.9,0.0,8.517950e-07,2.447280e-07,0.000000e+00,0,35.0,23.0,22.982,"59.74,992.44",NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1309,08042021-06:35:13,10.9,10.899975,10.900029,10.9,0.0,5.312460e-07,1.790720e-07,0.000000e+00,0,35.0,23.0,22.680,"62.52,993.31",NaN,NaN
1310,08042021-06:35:20,10.9,10.899976,10.900029,10.9,0.0,5.356070e-07,1.649810e-07,0.000000e+00,0,35.0,23.0,22.680,"62.49,993.29",NaN,NaN
1311,08042021-06:35:27,10.9,10.899976,10.900029,10.9,0.0,6.437390e-07,2.198730e-07,0.000000e+00,0,35.0,23.0,22.679,"62.49,993.29",NaN,NaN
1312,08042021-06:35:35,10.9,10.899976,10.900029,10.9,0.0,5.955860e-07,2.123480e-07,0.000000e+00,0,35.0,23.0,22.685,"62.48,993.32",NaN,NaN
1313,08042021-06:35:42,10.9,10.899974,10.900029,10.9,0.0,6.691450e-07,2.105000e-07,1.776360e-15,0,35.0,23.0,22.683,"62.46,993.34",NaN,NaN

There are multiple measurements for each voltage point. Therefore, we group them and calculate the mean for every group

In [4]:
data = data.groupby(['source']).apply(np.mean)

Now we can calculate a least square fit

In [5]:
slope, intercept, rvalue, pvalue, stderr = stats.linregress(data["duta"], data[ref])

In [7]:
corr  = data["duta"] * slope - intercept
error = corr - data[ref]

plt.figure()
plt.title("Transmille INL")
plt.plot(data[ref], error, '.', label="measured error")

plt.ylabel("Deviation in V")
plt.xlabel("Input in V")
plt.grid()

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous â€¦